--- 
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      layout: post
layout: stacked
permalink: "/:year/:month/:day/:title/"
plugins: 
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
projects: 
  exclude: 
    forks: false
    projects: ~
  limit: 4
  sort_by: pushed
social_media: 
  facebook: osismpksmaniwa
  instagram: osismpksmaniwa
  twitter: omsmaniwa
  website: "http://web.osismpksmaniwa.web.id"
  youtube: osismpksmanegeri1wonoayu
style: dark
topics: 
  - 
    image_url: "https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png"
    name: CSS
    web_url: "https://github.com/topics/css"
  - 
    name: "Web design"
  - 
    image_url: "https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png"
    name: Sass
    web_url: "https://github.com/topics/sass"
